apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: product-db
  namespace: ecommerce-data
spec:
  serviceName: product-db
  replicas: 1
  selector:
    matchLabels:
      app: product-db
  template:
    metadata:
      labels:
        app: product-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "freshcart"
            - name: POSTGRES_PASSWORD
              value: "freshcart"
            - name: POSTGRES_DB
              value: "freshcart_products"
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 512Mi
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "freshcart"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "freshcart"]
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          emptyDir: {}
