apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: ecommerce
data:
  SERVICE_NAME: "user-service"
  SERVICE_PORT: "8081"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger.observability.svc.cluster.local:4318"
  OTEL_SERVICE_NAME: "user-service"
