apiVersion: v1
kind: Secret
metadata:
  name: freshcart-secrets
  namespace: ecommerce
type: Opaque
stringData:
  JWT_SECRET: "freshcart-dev-secret"
  USER_DB_URL: "postgres://freshcart:freshcart@user-db.ecommerce-data.svc.cluster.local:5432/freshcart_users?sslmode=disable"
  PRODUCT_DB_URL: "postgres://freshcart:freshcart@product-db.ecommerce-data.svc.cluster.local:5432/freshcart_products?sslmode=disable"
  ORDER_DB_URL: "postgres://freshcart:freshcart@order-db.ecommerce-data.svc.cluster.local:5432/freshcart_orders?sslmode=disable"
  MONGODB_URI: "mongodb://notification-db.ecommerce-data.svc.cluster.local:27017"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq.ecommerce-data.svc.cluster.local:5672/"
